//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunz.Microservice.WebTests
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;


    public class WebTest1Coded : WebTest
    {

        public WebTest1Coded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            WebTestRequest request1 = new WebTestRequest("http://localhost:53708/api/v1/orders");
            request1.Encoding = System.Text.Encoding.GetEncoding("utf-8");
            request1.QueryStringParameters.Add("pageIndex", "1", false, false);
            request1.QueryStringParameters.Add("pageSize", "10", false, false);
            yield return request1;
            request1 = null;
        }
    }
}
